import type { Metadata } from 'next'
import Link from 'next/link'
import { activities, getActivitiesByCategory } from '@/lib/data/activities'
import { guides, getGuidesByCategory } from '@/lib/data/guides'
import { ActivityCard } from '@/components/ui/ActivityCard'
import { GuideCard } from '@/components/ui/GuideCard'
import { SectionHeader } from '@/components/ui/SectionHeader'

/* ─── SEO metadata ───────────────────────────────────────────────── */
export const metadata: Metadata = {
  title: 'Surf in Fuerteventura — Spots, Lessons & Local Guide',
  description:
    'Everything you need to know about surfing in Fuerteventura: best surf spots, beginner lessons, intermediate coaching and the honest local perspective on when and where to go.',
  alternates: { canonical: 'https://explorefuerteventura.com/surf-fuerteventura' },
  openGraph: {
    title: 'Surf in Fuerteventura — Spots, Lessons & Local Guide',
    description:
      'The definitive local guide to surf in Fuerteventura. Best spots, lesson options and honest advice — no fluff.',
  },
}

const FAQ_ITEMS = [
  {
    question: 'Is Fuerteventura good for beginner surfers?',
    answer:
      'Yes — especially in summer (May–September) when swells are smaller and conditions are more forgiving. The north-facing beaches near Corralejo offer excellent beach breaks for beginners.',
  },
  {
    question: 'What is the best time of year to surf in Fuerteventura?',
    answer:
      'For beginners: May to September. For intermediate/advanced surfers: October to March, when Atlantic storms send consistent, powerful swells. The island receives rideable waves year-round.',
  },
  {
    question: 'Do I need my own board and wetsuit?',
    answer:
      'Not for lessons — all equipment is included. For independent surfing, you can rent boards and wetsuits at several shops in Corralejo and El Cotillo.',
  },
  {
    question: 'How warm is the water?',
    answer:
      'The Atlantic around Fuerteventura ranges from around 18°C in winter to 23°C in summer. A 3/2mm wetsuit covers you most of the year; some locals go boardshorts-only in August.',
  },
]

const surfSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ_ITEMS.map(faq => ({
    '@type': 'Question',
    name: faq.question,
    acceptedAnswer: { '@type': 'Answer', text: faq.answer },
  })),
}

export default function SurfFuerteventuraPage() {
  const surfActivities = getActivitiesByCategory('surf')
  const surfGuides     = getGuidesByCategory('surf')

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(surfSchema) }}
      />

      {/* SEO hero */}
      <div className="bg-gradient-to-br from-ocean-900 to-ocean-700 pt-32 pb-16 md:pt-40 md:pb-24">
        <div className="container-main max-w-3xl">
          <nav aria-label="Breadcrumb" className="mb-6">
            <ol className="flex items-center gap-2 text-sm text-ocean-300">
              <li><Link href="/" className="hover:text-white transition-colors">Home</Link></li>
              <li aria-hidden="true" className="text-ocean-600">›</li>
              <li aria-current="page" className="text-white">Surf in Fuerteventura</li>
            </ol>
          </nav>
          <h1 className="font-heading font-extrabold text-white text-[clamp(2rem,5vw,3.5rem)] leading-tight mb-5">
            Surf in Fuerteventura
          </h1>
          <p className="text-ocean-200 text-lg md:text-xl leading-relaxed">
            One of Europe's most consistent surf destinations — year-round waves,
            warm sun and a coastline with something for every level.
            Here's the honest local guide to surfing here.
          </p>
        </div>
      </div>

      {/* Intro content — SEO text */}
      <section className="section-padding bg-white">
        <div className="container-main">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 lg:gap-16 max-w-5xl">
            <div className="space-y-5 text-[var(--color-text-muted)] leading-relaxed">
              <h2 className="font-heading font-bold text-2xl text-[var(--color-text)]">
                Why surf in Fuerteventura?
              </h2>
              <p>
                Fuerteventura sits at the northern edge of the Canary Islands, directly in the path of
                Atlantic swells generated by storms off North America and Iceland. The result: remarkably
                consistent surf throughout the year, clean water and predictable conditions that make it
                ideal for learning and progressing.
              </p>
              <p>
                Unlike mainland Spain, the water stays rideable year-round — even in winter, when big
                swells roll in, it rarely drops below 18°C. In summer, gentle waist-high waves and
                near-flat trade winds create the perfect conditions for beginners.
              </p>
            </div>
            <div className="space-y-5 text-[var(--color-text-muted)] leading-relaxed">
              <h2 className="font-heading font-bold text-2xl text-[var(--color-text)]">
                Best surf spots by level
              </h2>
              <ul className="space-y-3">
                {[
                  { spot: 'Playa de Corralejo',    level: 'Beginner',     desc: 'Long beach break, forgiving and well-monitored.' },
                  { spot: 'El Hierro (La Pared)',  level: 'Intermediate', desc: 'Powerful left-handers, consistent year-round.'    },
                  { spot: 'Punta Blanca',          level: 'Advanced',     desc: 'Reef break, strong current, serious waves.'       },
                  { spot: 'Los Lobos Island',      level: 'Advanced',     desc: 'World-class right-hander, boat access required.'  },
                ].map(({ spot, level, desc }) => (
                  <li key={spot} className="flex gap-3">
                    <span className="w-5 h-5 mt-0.5 rounded-full bg-ocean-100 text-ocean-600 shrink-0 flex items-center justify-center text-xs">🌊</span>
                    <div>
                      <strong className="text-[var(--color-text)] font-semibold">{spot}</strong>
                      <span className="mx-2 text-xs text-ocean-500">— {level}</span>
                      <span>{desc}</span>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Surf activities */}
      <section className="section-padding bg-[var(--color-bg)]">
        <div className="container-main">
          <SectionHeader
            eyebrow="Surf Experiences"
            title="Book a Surf Session"
            subtitle="Beginner lessons, intermediate coaching and spots tours — all with local instructors."
            titleAs="h2"
          />
          <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {surfActivities.map((a, i) => (
              <ActivityCard key={a.slug} activity={a} priority={i === 0} />
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section-padding bg-white">
        <div className="container-main max-w-3xl">
          <SectionHeader
            eyebrow="FAQ"
            title="Surf Fuerteventura — Common Questions"
            titleAs="h2"
          />
          <dl className="mt-10 space-y-6">
            {FAQ_ITEMS.map(({ question, answer }) => (
              <div key={question} className="border-b border-gray-100 pb-6">
                <dt className="font-heading font-bold text-lg text-[var(--color-text)] mb-2">
                  {question}
                </dt>
                <dd className="text-[var(--color-text-muted)] leading-relaxed">{answer}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      {/* Related guides */}
      {surfGuides.length > 0 && (
        <section className="section-padding bg-[var(--color-bg)]">
          <div className="container-main">
            <SectionHeader eyebrow="Read More" title="Surf Guides" titleAs="h2" />
            <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {surfGuides.slice(0, 3).map(g => (
                <GuideCard key={g.slug} guide={g} />
              ))}
            </div>
          </div>
        </section>
      )}
    </>
  )
}
